### PR TITLE
allow not submitting of form on pressing enter within input field

### PR DESCRIPTION
**Pull request by mdulat**
Required for https://github.com/Brightspace/d2l-rubric/pull/106

### CODE REVIEW

**Comment by mdulat** [comment]
@dlockhart @awikkerink it isn't clear to me why this build is failing, looks like it timed out. Something I need to investigate, or is it just because this is a fork?

**Comment by awikkerink** [comment]
What is the case this change is trying to address?

**Comment by mdulat** [comment]
This allows a user of the component to indicate that form submission should not happen when a user presses Enter within the input field.

**Comment by mdulat** [comment]
Currently in our rubrics Edit views, which live within a form, we are using this component, and when the user presses Enter, the form is submitted. We would like for no action to occur in this case.

**Comment by awikkerink** [comment]
Why not catch the events in rubrics? Something like

```html
<form id="form" on-submit="_preventSubmitHandler">
...
<input type="submit" on-click="_submitForm">
</form>
```

```javascript
_submitForm: function() {
    this.form.submit();
}
```

This would also prevent other elements from submitting the form.

**Comment by mdulat** [comment]
The form isn't within our component (d2l-rubric), it's within the LMS which houses our component, so we don't want to modify it directly.

**Comment by mdulat** [comment]
Yes probably for types that automatically submit. For rubrics we also have textareas, but they don't submit the form on Enter.
I don't have permissions to merge to this repo. If you're ok with it, can you merge it?

**Comment by dlockhart** [comment]
@mdulat @awikkerinkSorry, I was away on vacation. This isn't actually needed at all -- just set the type to "button", `<d2l-text-input type="button">`. By default, the type is "submit", which has the behaviour you described of submitting the form when the user hits enter.

**Pull request merged**
